version: "3"
services:
  game-server:
    build:
      context: .
      dockerfile: ./docker/local/Dockerfile
    environment:
      - ENV
      - PORT
      - API_ADDRESS
    volumes:
      - ./:/go/src/github.com/CA22-game-creators/cookingbomb-gameserver
    restart: always
    tty: true
    ports:
      - "8085:8085"
    networks:
      - "shared-local"

networks:
  shared-local:
    external: true
