version: "3"
services:
  game-server:
    build:
      context: .
      dockerfile: ./docker/local/Dockerfile
    volumes:
      - ./:/go/src/app
    restart: always
    tty: true
    ports:
      - "8085:8085"
