name: test_and_lint

on:
  pull_request:
    types: [opened, synchronize]
    paths-ignore:
      - "**.md"

jobs:
  # TODO test
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29
          args: --enable=golint,gosec,prealloc,gocognit
